### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by Xupeng-Wang** [bobo0810/PytorchNetHub#1]
你好，我在win10上运行该程序遇到了如下报错：RuntimeError: The shape of the mask [32, 8732] at index 0 does not match the shape of the indexed tensor [279424, 1] at index 0 不知道你有什么解决办法吗。

**Comment by bobo0810** [comment]
请问你是运行哪个项目出现的？目测应该是pytorch版本不对，目前仅YOLO v3支持 Windows版pytorch0.4。0.4之前版本没有Windows版本
