### ISSUE TITLE
pytorch1.0 RuntimeError: CUDA out of memory  （yolov1）

### ISSUE THREAD

**Issue by lijukun** [bobo0810/PytorchNetHub#10]
在1.0下跑，刚开始gpu就没内存了，没找到原因。
line 119, in train
    loss.backward()
  File "/home/dawn/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/dawn/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 23.00 MiB (GPU 0; 1.95 GiB total capacity; 1.46 GiB already allocated; 18.19 MiB free; 7.47 MiB cached)

**Comment by bobo0810** [comment]
@lijukun 抱歉，刚看到。
应该就是GPU没内存了，我使用实验室的服务器，总共22G，不担心内存问题。
建议：
- 先跑 测试，没问题说明环境及硬件配置好了。再看训练部分。
- debug模式一步一步调试，查找问题。
