### ISSUE TITLE
请教一个YOLOv1的内容

### ISSUE THREAD

**Issue by VictorSun1996** [bobo0810/PytorchNetHub#11]
file_root = '/home/zhuhui/data/VOCdevkit/VOC2012/JPEGImages/'  #VOC2012的训练集
    test_root = '/home/zhuhui/data/VOCdevkit/VOC2007/JPEGImages/'   #VOC2007的测试集
    train_Annotations = '/home/zhuhui/data/VOCdevkit/VOC2012/Annotations/'
    voc_2007test='/home/bobo/PycharmProjects/torchProjectss/YOLOv1ByBobo/data/voc2007test.txt'
    voc_2012train='/home/bobo/PycharmProjects/torchProjectss/YOLOv1ByBobo/data/voc2012train.txt'

    test_img_dir='/home/bobo/PycharmProjects/torchProjectss/YOLOv1ByBobo/testImgs/a.jpg'
    result_img_dir='/home/bobo/PycharmProjects/torchProjectss/YOLOv1ByBobo/testImgs/result_a.jpg'

在config.py文件中，这些是什么意思呢？好像自己的电脑也没有这些文件夹，要怎么创立使用呢？谢谢答疑

**Comment by bobo0810** [comment]
@victory2410 你好，抱歉刚看到。test_img_dir是 测试图片的路径，result_img_dir是  测试结果保存的路径。
