### ISSUE TITLE
CPU占用高，而GPU占用低

### ISSUE THREAD

**Issue by LewX** [bobo0810/PytorchNetHub#2]
请问大佬，我用自己的数据集训练YOLO的时候CPU占用很高（100%），而GPU使用率只有10%左右，显存占用倒是有60-70%，请问是什么原因导致的呢？怎样提高GPU的使用率？

**Comment by bobo0810** [comment]
请问你是yolo v1 还是yolo v3？我倒没碰到这个问题。想提高GPU使用率可以考虑增大batch size ，如果是多GPU，考虑多GPU并行。

**Comment by LewX** [comment]
> 请问你是yolo v1 还是yolo v3？我倒没碰到这个问题。想提高GPU使用率可以考虑增大batch size ，如果是多GPU，考虑多GPU并行。

你好，我是用的yolo v3，也就是你添加了注释的代码。增大batch size会导致报错（估计是显存不够。。）另外我用自己训练的模型做测试的时候，结果不对，基本上是满屏的框框，不知道是训练数据的原因还是其他什么原因导致的，也可能是训练次数不够？还有个问题想请教，标签label的正确格式是怎样的呢？我这里用的是yolo官方的训练voc转换之后的label，即[类, x, y, w, h] （大小范围0-1），不知道我用对没有，还请大佬讲解。

**Comment by bobo0810** [comment]
> 你好，我是用的yolo v3，也就是你添加了注释的代码。增大batch size会导致报错（估计是显存不够。。）另外我用自己训练的模型做测试的时候，结果不对，基本上是满屏的框框，不知道是训练数据的原因还是其他什么原因导致的，也可能是训练次数不够？还有个问题想请教，标签label的正确格式是怎样的呢？我这里用的是yolo官方的训练voc转换之后的label，即[类, x, y, w, h] （大小范围0-1），不知道我用对没有，还请大佬讲解。

你好，原仓库在COCO数据集训练，没加入VOC数据集。另外，刚看到原仓库8天前有更新，你可以去看看。（推荐  pytorch原生实现yolov3网络的仓库 https://github.com/BobLiu20/YOLOv3_PyTorch）
