### ISSUE TITLE
关于训练的问题

### ISSUE THREAD

**Issue by ming71** [bobo0810/PytorchNetHub#5]
请问为什么我改为自己的单类目标检测，训练自己标注的数据（不在coco的80类里面）
ground truth使用的是原作者最后使用的0-1的归一化xywh
结果那训练集进行检测，什么都检测不出来？是不是这里的ground truth格式不对？

**Comment by bobo0810** [comment]
你好，你具体说哪个项目呢？

我之前参加比赛也用过YOLO v1做目标检测，没有任何问题。
参见[https://github.com/bobo0810/XueLangTianchi ](url)    其中的提交历史
  ![](http://boboprivate.oss-cn-beijing.aliyuncs.com/19-3-22/ed7417989a0127b0162ac950ccfc492.png)

**Comment by bobo0810** [comment]
@ming71
