### ISSUE TITLE
关于数据集存放的问题

### ISSUE THREAD

**Issue by gm0515** [bobo0810/PytorchNetHub#6]
您好，请问咱们这个模型的数据集是不是COCO格式的，我之前是VOC格式的。

如果是的话，我已经转换成COCO格式了，但是请问这个数据集格式应该放在哪个文件夹里面。

现在训练的时候好像没有读取我的训练集，自己也训练了，我找了好久也不知道数据集应该放在哪里。

是不是训练的图片和.json文件需要一起放到你config.py指定的samples文件夹里面。

**Comment by bobo0810** [comment]
你好，请问是哪个项目呢？

**Comment by gm0515** [comment]
> 你好，请问是哪个项目呢？

YOLO v3的

**Comment by bobo0810** [comment]
> > 你好，请问是哪个项目呢？
> 
> YOLO v3的

你好，是coco格式的，请详细看下`AnnotatedNetworkModelGit/Yolov3_pytorch/data/get_coco_dataset.sh`
该文件将对你提供帮助

**Comment by gm0515** [comment]
> > > 你好，请问是哪个项目呢？
> > 
> > 
> > YOLO v3的
> 
> 你好，是coco格式的，请详细看下`AnnotatedNetworkModelGit/Yolov3_pytorch/data/get_coco_dataset.sh`
> 该文件将

**Comment by gm0515** [comment]
> > > 你好，请问是哪个项目呢？
> > 
> > 
> > YOLO v3的
> 
> 你好，是coco格式的，请详细看下`AnnotatedNetworkModelGit/Yolov3_pytorch/data/get_coco_dataset.sh`
> 该文件将对你提供帮助

那请问，如果我想用自己的数据集，我该如何操作。我是不是也要将之前的VOC格式生成.sh文件。

**Comment by bobo0810** [comment]
你好  .sh文件是脚本文件。我的意思是  
1、先使用VOC数据集，使用get_coco_dataset.sh生成最后可用的数据集格式
2、看懂get_coco_dataset.sh脚本里的代码，明白 它究竟是如何处理数据集的
3、参照VOC生成结果，并结合.sh的处理方式，将你自己的数据集进行类似处理
